# Generated by Django 5.0.1 on 2024-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_learner_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learner'),
        ),
    ]
