# Generated by Django 5.0.1 on 2024-01-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_learner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='learner',
            new_name='user',
        ),
    ]
