version: '3'

# we use build comand to build our won image

services:
  # web:
  #   build: .      # it fill take default dockerfile and make image if your docker name is not same you have to mention it
  # we use build comand to build our won image

  #   command: python manage.py runserver 0.0.0.0:8000
    
  #   ports:
  #     - "8000:8000"

  ng:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - my-network
  alpineservice:
    image: alpine:latest
    ports:
      - "3000:3000"

    networks:
      - my-network


  db:
    image: mysql:latest
    
    environment:
      - MYSQL_ROOT_PASSWORD=9038
    networks:
      - my-network

networks:
  my-network:
    driver : bridge