# Generated by Django 5.0.1 on 2024-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instructor', '0005_leacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leacture',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
