# Generated by Django 5.0.1 on 2024-01-23 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Instructor', '0006_alter_leacture_order'),
        ('students', '0004_rename_learner_learner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instructor.course')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='students.learner')),
                ('items', models.ManyToManyField(related_name='cart_item', to='cart_app.cartitem')),
            ],
        ),
    ]
