# Generated by Django 5.0.1 on 2024-01-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified_tuitor',
            new_name='verified_instructor',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'learner'), ('instructor', 'instructor')], default='student', max_length=40),
        ),
    ]
