# Generated by Django 5.0.1 on 2024-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_user', '0002_rename_verified_tuitor_user_verified_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('learner', 'learner'), ('instructor', 'instructor')], default='learner', max_length=40),
        ),
    ]
